-- Select the database

DROP TABLE IF EXISTS amenities CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS gymes CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS gym_amenity CASCADE;
DROP TABLE IF EXISTS client_gymes CASCADE;